@startuml
 !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

 LAYOUT_LANDSCAPE()

 title
  <b>[Systen Context] Система мониторинга свиноводческих ферм</b>
 end title

 Person(prod_owner, "Директор хозяйства")
 Person(analytic, "Аналитик")
 Person(feed_mng, "Комплекс управления кормлением")
 Person(animal_watcher, "Скотовод")

 Container(msa_agrotech_system, "MSA-AgroTech", "system", "Мониторинг и управление кормлением скота, мониторинг состояния и поведения скота, анализ данных")
  
 Rel(prod_owner, msa_agrotech_system, "Использует")
 Rel(analytic, msa_agrotech_system, "Анализирует")
 Rel(feed_mng, msa_agrotech_system, "Управляет")
 Rel(animal_watcher, msa_agrotech_system, "Мониторит")

 System_Ext(agrotech_system, "АгроТех Х", "Мониторинг и управление техникой, поливом, анализ данных ")
 System_Ext(analytic_module, "Аналитический модуль", "Анализирует поведение и состояние скота, прогнозирует расход воды и корма ")

 Rel(msa_agrotech_system, agrotech_system, "взаимодействует" )
 Rel(msa_agrotech_system, analytic_module, "запрашивает" )

 @enduml